<form method="POST" action="{{ $action }}" class="space-y-5">@csrf @method($method)
    <div><label class="block text-sm font-medium">Título</label><input name="title" value="{{ old('title', $offer?->title) }}" required class="mt-1 w-full rounded border-gray-300"><x-input-error :messages="$errors->get('title')" /></div>
    <div class="grid gap-5 sm:grid-cols-2"><div><label class="block text-sm font-medium">Categoria</label><select name="category_id" required class="mt-1 w-full rounded border-gray-300"><option value="">Selecione</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id', $offer?->category_id) == $category->id)>{{ $category->name }}</option>@endforeach</select></div><div><label class="block text-sm font-medium">Loja</label><select name="store_id" required class="mt-1 w-full rounded border-gray-300"><option value="">Selecione</option>@foreach($stores as $store)<option value="{{ $store->id }}" @selected(old('store_id', $offer?->store_id) == $store->id)>{{ $store->name }}</option>@endforeach</select></div></div>
    <div><label class="block text-sm font-medium">Descrição</label><textarea name="description" rows="4" class="mt-1 w-full rounded border-gray-300">{{ old('description', $offer?->description) }}</textarea></div>
    <div class="grid gap-5 sm:grid-cols-2"><div><label class="block text-sm font-medium">Preço atual</label><input type="number" step="0.01" min="0" name="current_price" value="{{ old('current_price', $offer?->current_price) }}" required class="mt-1 w-full rounded border-gray-300"></div><div><label class="block text-sm font-medium">Preço anterior</label><input type="number" step="0.01" min="0" name="old_price" value="{{ old('old_price', $offer?->old_price) }}" class="mt-1 w-full rounded border-gray-300"></div></div>
    <div class="grid gap-5 sm:grid-cols-2"><div><label class="block text-sm font-medium">URL da imagem</label><input type="url" name="image_url" value="{{ old('image_url', $offer?->image_url) }}" class="mt-1 w-full rounded border-gray-300"></div><div><label class="block text-sm font-medium">URL de compra</label><input type="url" name="purchase_url" value="{{ old('purchase_url', $offer?->purchase_url) }}" required class="mt-1 w-full rounded border-gray-300"></div></div>
    <div class="grid gap-5 sm:grid-cols-2"><div><label class="block text-sm font-medium">Parcelamento</label><input name="installment_info" value="{{ old('installment_info', $offer?->installment_info) }}" placeholder="12x sem juros" class="mt-1 w-full rounded border-gray-300"></div><div><label class="block text-sm font-medium">Cupom</label><input name="coupon" value="{{ old('coupon', $offer?->coupon) }}" class="mt-1 w-full rounded border-gray-300"></div></div>
    <div><label class="block text-sm font-medium">Validade</label><input type="datetime-local" name="expires_at" value="{{ old('expires_at', $offer?->expires_at?->format('Y-m-d\TH:i')) }}" class="mt-1 rounded border-gray-300"></div>
    <label class="flex items-center gap-2"><input type="checkbox" name="is_featured" value="1" @checked(old('is_featured', $offer?->is_featured))> Oferta em destaque</label><label class="flex items-center gap-2"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $offer?->is_active ?? true))> Oferta ativa</label>
    <div class="flex justify-end gap-3"><a href="{{ route('offers.index') }}" class="rounded border px-4 py-2">Cancelar</a><button class="rounded bg-indigo-600 px-4 py-2 font-semibold text-white">Salvar oferta</button></div>
</form>
